### ISSUE TITLE
Layout doesn't stabilize

### ISSUE THREAD

**Issue by BenWiederhake** [evanandrewrose/cargo-vis#1]
Nice work!  But is it intentional that sometimes the layout doesn't always stabilize?  I was actually mostly impressed by the awesome layouting algorithm, and that it quickly settles into a specific configuration without "sliding" all the time, as I've seen with other tools.

How to reproduce:
Sadly, I'm not sure where and how I prodded to make this happen, but pushing the `winapi-*` crates together and then swapping `atty` and `termsize` forth and back seems like a good way.  I could reproduce it three out of three times.

[Here's a recording](https://imgur.com/a/ZaM8K).
Console doesn't say anything.

**Comment by evanandrewrose** [comment]
@BenWiederhake 

Thanks for the bug report. I was able to quickly reproduce it with the termsize crate. I updated the graph physics parameters in abce5d331678e4973065ae3167b00a5fa1ffda9a. The layout is a lot more stable now and I haven't seen the issue since. Be sure to test in an incognito window to avoid caching.

Let me know if this resolves the issue.

Evan

**Comment by BenWiederhake** [comment]
Looks good to me
